####################
# FRONTEND BUILDER #
####################

FROM node:16-slim as builder

WORKDIR /usr/src/app

# Install dependencies according to yarn.lock file
COPY ./yarn.lock /usr/src/app/
COPY ./package.json /usr/src/app/
RUN yarn install --frozen-lockfile

# Copy rest of the source code
COPY . /usr/src/app/

# Clear dist directory if existing
RUN rm -rf "dist"/{*,.[!.]*}