# Generated by Django 3.2.10 on 2022-02-27 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Workspace Admins'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The workspace's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Workspace Members'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The workspace's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
