# Generated by Django 3.2.10 on 2022-02-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0010_temp_chunked_biginteger'),
        ('usermanagement', '0002_user_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='django_drf_filepond.storedupload', verbose_name='Profile picture'),
        ),
    ]
