# Generated by Django 3.2.10 on 2022-02-06 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Workspace Admins'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Workspace Members'),
        ),
    ]
