# Generated by Django 3.2.10 on 2022-02-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('usermanagement', '0004_auto_20220206_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The workspace's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The workspace's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
