# Generated by Django 3.1.5 on 2021-07-23 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20210723_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organisations',
        ),
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Organisation Members'),
        ),
    ]
