# Generated by Django 3.2.5 on 2021-07-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_alter_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='buttonText',
            field=models.CharField(default='Select', max_length=40, verbose_name='Button text'),
            preserve_default=False,
        ),
    ]
