# Generated by Django 3.2.5 on 2021-09-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0012_auto_20210909_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='subscription',
            new_name='subscriptionPlan',
        ),
    ]
