# Generated by Django 3.2.8 on 2021-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagement", "0014_workspace_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="termsAndConditionsAccepted",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether a user accepted the terms and conditions. Acceptance is required to use any functionality of the app.",
                verbose_name="Terms and Conditions accepted",
            ),
        ),
    ]
