# Generated by Django 3.2.8 on 2021-10-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagement", "0015_user_termsandconditionsaccepted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="termsAndConditionsAccepted",
            new_name="terms_and_conditions_accepted",
        ),
    ]
