# Generated by Django 3.2.9 on 2021-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0017_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_setup',
            field=models.BooleanField(default=False, help_text="Designates whether this user has been setup with additional information after their creation. This can be used for displaying a 'First Setup' page after login.", verbose_name='setup'),
        ),
    ]
