# Generated by Django 3.2.9 on 2021-11-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0018_user_is_setup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_setup',
            new_name='initial_setup_done',
        ),
    ]
