# Generated by Django 3.2.10 on 2022-02-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('usermanagement', '0019_rename_is_setup_user_initial_setup_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='city',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='country',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='paymentCycle',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='state',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='street',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='streetnumber',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='subscriptionPlan',
        ),
        migrations.AddField(
            model_name='workspace',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The workspace's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The workspace's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
