version: '3.9'

services:
  postgresql-db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgresqldb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saasboilerplatedb
      - POSTGRES_USER=saasboilerplatedbuser
      - POSTGRES_PASSWORD=saasboilerplatedbpassword

  backend-django:
    build: 
      context: ./backend
      dockerfile: Dockerfile.production
    image: saasboilerplate-backend:latest
    command: gunicorn saasboilerplate.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/backend/staticfiles
    expose:
      - 8000
    env_file:
      - ./backend/.env.production
    depends_on:
      - postgresql-db
  
  nginx:
    build: 
      context: ./
      dockerfile: nginx/Dockerfile.production
    image: saasboilerplate-nginx:latest
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/backend/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend-django

volumes:
  postgresqldb_data:
  static_volume: